export const SEED_CATEGORIES = [
  {
    slug: "sherwanis",
    name: "Sherwanis",
    tagline: "Handcrafted heirloom silhouettes for the modern groom.",
    imageFile: "cat-sherwani.jpg",
    subCategories: ["Silk & Zardosi", "Velvet Heritage", "Pastel Groom", "Floral Embroidered", "Ivory Classic"],
    sortOrder: 1,
  },
  {
    slug: "bandhgalas",
    name: "Bandhgalas",
    tagline: "Structured tailoring, mandarin collars, evening sovereignty.",
    imageFile: "cat-bandhgala.jpg",
    subCategories: ["Classic Black", "Emerald Velvet", "Prince Coats", "Nehru Jackets"],
    sortOrder: 2,
  },
  {
    slug: "wedding-suits",
    name: "Wedding Suits",
    tagline: "Italian construction, Indian soul.",
    imageFile: "cat-groom.jpg",
    subCategories: ["Three-Piece", "Tuxedos", "Ivory Suits", "Charcoal Formal"],
    sortOrder: 3,
  },
  {
    slug: "indo-western",
    name: "Indo-Western",
    tagline: "Draped kurtas, layered jackets, contemporary silhouettes.",
    imageFile: "cat-indowestern.jpg",
    subCategories: ["Draped Kurtas", "Asymmetric Sets", "Jacket Kurtas", "Cowl Pants"],
    sortOrder: 4,
  },
  {
    slug: "occasion-kurtas",
    name: "Occasion Kurtas",
    tagline: "Silk kurta sets for every celebration.",
    imageFile: "product-1.jpg",
    subCategories: ["Chikankari", "Silk Sets", "Bandi Jackets", "Angrakha"],
    sortOrder: 5,
  },
  {
    slug: "accessories",
    name: "Accessories",
    tagline: "Finishing details — safas, stoles, brooches.",
    imageFile: "cat-accessories.jpg",
    subCategories: ["Safa Turbans", "Stoles", "Brooches", "Pocket Squares", "Mojaris"],
    sortOrder: 6,
  },
];

export const SEED_PRODUCTS = [
  {
    slug: "the-rosewood-sherwani",
    name: "The Rosewood Sherwani",
    categorySlug: "sherwanis",
    fabric: "Rose Silk & Zardosi",
    price: 74000,
    imageFile: "product-1.jpg",
    description:
      "A blush pink silk sherwani hand-embroidered with pearl and zardosi motifs. Cut on the Delhi last with a slim, tailored silhouette.",
    isNew: true,
    bestSeller: true,
  },
  {
    slug: "royal-emerald-bandhgala",
    name: "Royal Emerald Bandhgala",
    categorySlug: "bandhgalas",
    fabric: "Pure Italian Velvet",
    price: 118000,
    imageFile: "product-2.jpg",
    description: "Deep emerald Italian velvet, structured shoulder line, hand-cast antique gold buttons.",
    isNew: true,
    bestSeller: true,
  },
  {
    slug: "heritage-ivory-suit",
    name: "Heritage Ivory Wedding Suit",
    categorySlug: "wedding-suits",
    fabric: "Raw Ivory Silk",
    price: 185000,
    imageFile: "product-3.jpg",
    description: "A three-piece ivory silk suit with tonal embroidery along the placket.",
    bestSeller: true,
  },
  {
    slug: "midnight-zardosi-kurta",
    name: "Midnight Zardosi Kurta",
    categorySlug: "occasion-kurtas",
    fabric: "Midnight Blue Silk",
    price: 42000,
    imageFile: "product-4.jpg",
    description: "Deep midnight blue silk kurta with intricate zardosi work at the collar and yoke.",
    isNew: true,
  },
  {
    slug: "imperial-maroon-sherwani",
    name: "The Imperial Maroon Sherwani",
    categorySlug: "sherwanis",
    fabric: "Velvet, Gold Thread",
    price: 240000,
    imageFile: "cat-groom.jpg",
    description: "Deep maroon velvet with hand-crafted gold zardosi from collar to hem.",
    bestSeller: true,
  },
  {
    slug: "onyx-bandhgala",
    name: "The Onyx Bandhgala",
    categorySlug: "bandhgalas",
    fabric: "Onyx Wool Blend",
    price: 96000,
    imageFile: "cat-bandhgala.jpg",
    description: "Jet-black bandhgala with subtle collar embroidery and antique gold buttons.",
  },
  {
    slug: "atelier-drape-kurta",
    name: "Atelier Drape Set",
    categorySlug: "indo-western",
    fabric: "Ivory Cotton Silk",
    price: 58000,
    imageFile: "cat-indowestern.jpg",
    description: "Ivory drape kurta with tailored trousers and a taupe overcoat.",
    isNew: true,
  },
  {
    slug: "atelier-sherwani-ivory",
    name: "The Atelier Sherwani",
    categorySlug: "sherwanis",
    fabric: "Ivory Silk",
    price: 88000,
    imageFile: "cat-sherwani.jpg",
    description: "Ivory silk sherwani with pearl and thread work along the placket.",
    bestSeller: true,
  },
];
